### PR TITLE
feat: support release

### PR DESCRIPTION
**Pull request by stew-ro**

### CODE REVIEW

**Comment by alex-krasn** [comment]
got this error:
Screen Shot 2020-06-26 at 12 04 34 PM

**Comment by stew-ro** [comment]
> got this error:
> Screen Shot 2020-06-26 at 12 04 34 PM



> got this error:
> Screen Shot 2020-06-26 at 12 04 34 PM

`yarn install` and maybe restart ide

**Comment by xinase** [comment]
> _No description provided._

hi, do we need to provide people with instructions to build and deploy the electron app locally on their machine?

**Comment by stew-ro** [comment]
> > _No description provided._
> 
> hi, do we need to provide people with instructions to build and deploy the electron app locally on their machine?

Hi. I added the following to the README:
_____
image
_____
Disregard my previous comment: "yarn install and maybe restart ide." The user won't get that error anymore and it's not required.

If the README isn't clear, let me know

**Comment by alex-krasn** [comment]
on Mac when creating project the app sets default project name as "process.platform"
Screen Shot 2020-06-30 at 10 55 46 AM

**Pull request merged**
